version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: mistral
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0

  api:
    build: ./fastapi_gateway
    container_name: mistral_api
    restart: always
    depends_on:
      - ollama
    ports:
      - "8080:8080"
    environment:
      - API_KEY=shyam_secret_key
      - OLLAMA_URL=http://ollama:11434

volumes:
  ollama:
